/*
  Summary.jsx
  -----------
  The escalation summary screen. This page loads a saved
  session from the backend using the session id in the URL
  and displays a clean readable summary of the full
  troubleshooting session.

  The user can copy the summary to their clipboard and
  paste it into a message to a support agent. This means
  the agent knows exactly what was tried without having
  to ask the same questions again.
*/

import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import './Summary.css'

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000'

function Summary() {

  const { sessionId } = useParams()
  const navigate = useNavigate()

  // Store the session data loaded from the backend
  const [session, setSession] = useState(null)

  // Track loading state
  const [loading, setLoading] = useState(true)

  // Track any error
  const [error, setError] = useState(null)

  // Track whether the copy was successful
  const [copied, setCopied] = useState(false)

  // Load the session from the backend when the page opens
  useEffect(() => {
    const fetchSession = async () => {
      try {
        setLoading(true)
        const response = await fetch(`${BASE_URL}/api/sessions/${sessionId}`)
        if (!response.ok) {
          throw new Error('Session not found')
        }
        const data = await response.json()
        setSession(data)
        setLoading(false)
      } catch (err) {
        setError('Could not load your session summary. Please try again.')
        setLoading(false)
      }
    }

    fetchSession()
  }, [sessionId])

  /*
    buildSummaryText
    ----------------
    Builds a plain text version of the session summary
    that the user can copy and paste into a support message.
  */
  const buildSummaryText = () => {
    if (!session) return ''

    const date = new Date(session.createdAt).toLocaleString()

    let text = `FixMyPhone Escalation Summary\n`
    text += `==============================\n`
    text += `Date: ${date}\n`
    text += `Category: ${session.categoryLabel}\n\n`

    text += `DIAGNOSIS\n`
    text += `---------\n`
    text += `Most likely cause: ${session.causeTitle}\n`
    text += `${session.causeDescription}\n\n`

    text += `QUESTIONS AND ANSWERS\n`
    text += `---------------------\n`
    session.answers.forEach((answer, index) => {
      text += `${index + 1}. ${answer.questionText}\n`
      text += `   Answer: ${answer.answerText}\n`
    })

    text += `\nFIX STEPS RECOMMENDED\n`
    text += `---------------------\n`
    session.fixSteps.forEach((fixStep) => {
      text += `${fixStep.step}. ${fixStep.title}\n`
      text += `   ${fixStep.detail}\n`
    })

    text += `\nGenerated by FixMyPhone`

    return text
  }

  /*
    handleCopy
    ----------
    Copies the plain text summary to the user's clipboard
    and shows a confirmation message for 2 seconds.
  */
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildSummaryText())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.log('Copy failed:', err)
    }
  }

  // Loading state
  if (loading) {
    return (
      <div className="summary-container">
        <div className="summary-loading">
          <p>Loading your summary...</p>
        </div>
      </div>
    )
  }

  // Error state
  if (error) {
    return (
      <div className="summary-container">
        <div className="summary-error">
          <p>{error}</p>
          <button onClick={() => navigate('/')}>Go Home</button>
        </div>
      </div>
    )
  }

  return (
    <div className="summary-container">

      {/* Header */}
      <div className="summary-header">
        <button
          className="summary-back-button"
          onClick={() => navigate(-1)}
        >
          ← Back
        </button>
        <span className="summary-header-label">Escalation Summary</span>
      </div>

      {/* Intro text */}
      <p className="summary-intro">
        Copy this summary and share it with your support agent so they
        know exactly what was tried and what the diagnosis was.
      </p>

      {/* Copy button */}
      <button
        className={`summary-copy-button ${copied ? 'copied' : ''}`}
        onClick={handleCopy}
      >
        {copied ? '✓ Copied to clipboard' : 'Copy summary to clipboard'}
      </button>

      {/* Session details */}
      <div className="summary-card">
        <div className="summary-meta">
          <p className="summary-meta-label">Category</p>
          <p className="summary-meta-value">{session.categoryLabel}</p>
        </div>
        <div className="summary-meta">
          <p className="summary-meta-label">Date</p>
          <p className="summary-meta-value">
            {new Date(session.createdAt).toLocaleString()}
          </p>
        </div>
      </div>

      {/* Diagnosis */}
      <div className="summary-section">
        <h3 className="summary-section-title">Diagnosis</h3>
        <div className="summary-card">
          <p className="summary-cause-title">{session.causeTitle}</p>
          <p className="summary-cause-description">{session.causeDescription}</p>
        </div>
      </div>

      {/* Questions and answers */}
      <div className="summary-section">
        <h3 className="summary-section-title">Questions and answers</h3>
        <div className="summary-qa-list">
          {session.answers.map((answer, index) => (
            <div key={answer._id} className="summary-qa-item">
              <p className="summary-question">
                {index + 1}. {answer.questionText}
              </p>
              <p className="summary-answer">→ {answer.answerText}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Fix steps */}
      <div className="summary-section">
        <h3 className="summary-section-title">Fix steps recommended</h3>
        <div className="summary-fix-steps">
          {session.fixSteps.map((fixStep) => (
            <div key={fixStep.step} className="summary-fix-step">
              <div className="summary-step-number">{fixStep.step}</div>
              <div>
                <p className="summary-step-title">{fixStep.title}</p>
                <p className="summary-step-detail">{fixStep.detail}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Home button */}
      <button
        className="summary-home-button"
        onClick={() => navigate('/')}
      >
        Back to Home
      </button>

    </div>
  )
}

export default Summary